# Generated by Django 4.1 on 2022-08-10 04:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='operation_logs',
            new_name='OperationLogs',
        ),
    ]
